services:
  frontend:
    build:
      context: ../../
      dockerfile: deploy/dockers/Dockerfile-frontend
    environment:
      INNER_FRONTEND_PORT: ${INNER_FRONTEND_PORT}
      OUTER_FRONTEND_PORT: ${OUTER_FRONTEND_PORT}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    ports:
      - "${OUTER_FRONTEND_PORT}:${INNER_FRONTEND_PORT}"
    networks:
      - nw

networks:
  nw:
    driver: bridge

